pub mod user_record;
pub mod current_user;
pub mod app_state;
pub mod add_traffic_form;
pub mod change_os_form;
pub mod resize_form;
pub mod base_state;
pub mod region_selection_form_step1;
pub mod network_configuration_form_step2;
pub mod custom_plan_specification_form_step3;
pub mod ssh_key_selection_form_step7;
pub mod region;
pub mod product_entry;
pub mod product_view;
pub mod os_item;
pub mod application_view;
pub mod instance_view;
pub mod ssh_key_view;
pub mod ssh_key_display;
pub mod extras;
pub mod plan_state;
pub mod user_row;
pub mod admin_view;

// Re-export all models
pub use user_record::UserRecord;
pub use current_user::CurrentUser;
pub use app_state::AppState;
pub use add_traffic_form::AddTrafficForm;
pub use change_os_form::ChangeOsForm;
pub use resize_form::ResizeForm;
pub use base_state::BaseState;
pub use region_selection_form_step1::RegionSelectionFormStep1;
pub use network_configuration_form_step2::NetworkConfigurationFormStep2;
pub use custom_plan_specification_form_step3::CustomPlanSpecificationFormStep3;
pub use ssh_key_selection_form_step7::SshKeySelectionFormStep7;
pub use region::Region;
pub use product_entry::ProductEntry;
pub use product_view::ProductView;
pub use os_item::OsItem;
pub use application_view::ApplicationView;
pub use instance_view::InstanceView;
pub use ssh_key_view::SshKeyView;
pub use ssh_key_display::SshKeyDisplay;
pub use extras::Extras;
pub use plan_state::PlanState;
pub use user_row::UserRow;
pub use admin_view::{AdminView, InstanceCheckbox};

// Type aliases for backward compatibility
pub type Step1FormData = RegionSelectionFormStep1;
pub type Step2FormData = NetworkConfigurationFormStep2;
pub type CustomPlanFormValues = CustomPlanSpecificationFormStep3;
pub type Step7Form = SshKeySelectionFormStep7;
